// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhl7GRE3g3dhk6MB4lqxbTxXPyFknatUw',
    appId: '1:1035842953230:web:4774b898ed4932dbf6dc5f',
    messagingSenderId: '1035842953230',
    projectId: 'logletter-6e3b2',
    authDomain: 'logletter-6e3b2.firebaseapp.com',
    storageBucket: 'logletter-6e3b2.appspot.com',
    measurementId: 'G-33FPFL51G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqMSpyiRRFEXn_zadUMrXldr4eMJgKTlE',
    appId: '1:1035842953230:android:7858abcee1ecbd94f6dc5f',
    messagingSenderId: '1035842953230',
    projectId: 'logletter-6e3b2',
    storageBucket: 'logletter-6e3b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUvGmD-hj34u-m2k9FZGSYSBiUGWjIzS8',
    appId: '1:1035842953230:ios:a489606872157366f6dc5f',
    messagingSenderId: '1035842953230',
    projectId: 'logletter-6e3b2',
    storageBucket: 'logletter-6e3b2.appspot.com',
    iosBundleId: 'com.example.logletter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUvGmD-hj34u-m2k9FZGSYSBiUGWjIzS8',
    appId: '1:1035842953230:ios:9861ab9b76f7b930f6dc5f',
    messagingSenderId: '1035842953230',
    projectId: 'logletter-6e3b2',
    storageBucket: 'logletter-6e3b2.appspot.com',
    iosBundleId: 'com.example.logletter.RunnerTests',
  );
}
